spring:
  application:
    name: manager-app
  datasource:
    url: jdbc:postgresql://localhost:5433/manager
    username: manager
    password: manager
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8082/realms/selmag
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: manager-app
            client-secret: Cj1kxisttbmgDfZvBRvUJVjX70CV5MSM
            scope:
              - openid
              - view_catalogue
              - edit_catalogue
              - microprofile-jwt

selmag:
  services:
    catalogue:
      uri: http://localhost:8081
      registration-id: keycloak